services:
  grabber_dev:
    image: grabber_image
    build:
      context: . 
      dockerfile: Dockerfile 
      args: # 设置构建时需要的代理参数
        http_proxy: "http://192.168.3.7:7897"
        https_proxy: "http://192.168.3.7:7897"
    # privileged: true 
    
    container_name: grabber_container
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/snd:/dev/snd # 挂载声卡

    ports:
      - "8888:8888" # 端口映射，允许外部通过8888端口访问容器内的服务，用于麦克风
      - "9889:9889" # 用于扬声器
    # 挂载卷
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # 挂载X11 socket
      - ~/.Xauthority:/root/.Xauthority:ro # 挂载X11授权文件
      
    # 这里定义容器运行时的环境变量
    environment:
      - http_proxy=http://192.168.3.7:7897
      - https_proxy=http://192.168.3.7:7897
      - no_proxy=localhost,127.0.0.1
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - NO_AT_BRIDGE=1 # 禁用AT-Bridge

    # 设置网络模式为host
    network_mode: "host"

    group_add:
      - audio # 添加音频组权限

    # 让容器可以访问GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # 让容器保持运行
    stdin_open: true
    # 交互式终端
    tty: true